sudo: required

env:
  global:
    - DOCKER_IMAGE=bskim45/helm-kubectl-jq
    - DOCKER_TAG=2.12.1

services:
  - docker

script:
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_IMAGE:latest .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
  - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  provider: script
  script: docker push $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:$DOCKER_TAG
  on:
    branch: master
